service: oshit

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  stage: ${opt:stage,'dev'}
  timeout: 10s

functions:
  addVictimToQueue:
    description: adds victim data from the oshit app to the SQS queue
    handler: src/handler.addVictimToQueue
    environment:
      STAGE: ${self:provider.stage}
      QUEUE_URL: ${env:QUEUE_URL}
    role: ${env:IAM_ROLE_SQS_FULL_ARN}
    events:
      - http:
          path: queue/add
          method: post
  log:
    description: logs the content of SQS messages
    handler: src/handler.log
    environment:
      STAGE: ${self:provider.stage}
    events:
      - sqs:
          arn: ${env:SQS_ARN}
          batchSize: 10
